### ISSUE TITLE
White on white text on stats page.

### ISSUE THREAD

**Issue by Jeklah** [Vagelis-Prokopiou/unsaferust.org#1]
As pointed out by redditors, white text on white background is being rendered on stats page.
This issue was not noticed due to dark-mode enabled in browser making the text readable.

On the default theme it is white on white, thus unreadable.

**Comment by Vagelis-Prokopiou** [comment]
Thanx @Jeklah. I reproduced it myself too.
Let's see what the solution is :-)

**Comment by Jeklah** [comment]
Excellent :)
I've found plugins to be the cause of bugs quite often!

**Comment by Vagelis-Prokopiou** [comment]
@Jeklah, PR #2  provided some fixes.
Can you verify that the issue is fixed?
The table headers are still problematic for the "Project details" pages, but we have some progress.

**Comment by Jeklah** [comment]
I can indeed verify this fix works! The text on home page and stats is now
black and very readable :)

**Comment by Jeklah** [comment]
And the table headers look good, nice and bold :)

**Comment by Vagelis-Prokopiou** [comment]
I have made the necessary changes to the theme, and now it uses a dark theme across the board. So, closing this.
Thanx for the collaboration.

**Comment by Jeklah** [comment]
No problem, glad to have helped!
