### ISSUE TITLE
Add unsafe ratio out of total lines

### ISSUE THREAD

**Issue by tuxiqae** [Vagelis-Prokopiou/unsaferust.org#4]
Consider adding a percentage which will describe the percentage of unsafe lines out of total lines in said project

**Comment by Vagelis-Prokopiou** [comment]
Yeap. I was thinking about it myself too. Since you asked, I will add it.
If you want you can try yourself.
If you do, do it on the client side.
Best approach would be to add it as a property as soon as you get the data from the service.
E.g.:
```
project_stats.forEach(i => i.percentage = i.unsafe_lines / i.code_lines)
```
Keep in mind for the case with 0 unsafe lines.

**Comment by Vagelis-Prokopiou** [comment]
Done with commit 112a6b3.
